---
name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending

exclude-labels:
  - 'skip-changelog'

categories:
  - title: "🚨 Breaking changes"
    labels:
      - "breaking-change"
  - title: "✨ New features"
    labels:
      - "new-feature"
  - title: "🐛 Bug fixes"
    labels:
      - "bugfix"
  - title: "🚀 Enhancements"
    labels:
      - "enhancement"
      - "refactor"
      - "performance"
  - title: "🌍 Endpoints"
    labels:
      - "endpoints"
  - title: "🧰 Maintenance"
    labels:
      - "maintenance"
      - "ci"
  - title: "📚 Documentation"
    labels:
      - "documentation"
  - title: "⬆️ Dependency updates"
    collapsed: true
    labels:
      - "dependencies"

version-resolver:
  major:
    labels:
      - "major"
      - "breaking-change"
  minor:
    labels:
      - "minor"
      - "new-feature"
  patch:
    labels:
      - "bugfix"
      - "chore"
      - "ci"
      - "dependencies"
      - "documentation"
      - "enhancement"
      - "performance"
      - "refactor"
  default: patch

template: |
  ## What’s changed
  $CHANGES
